name: Ze

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download Zrok
      run: Invoke-WebRequest https://github.com/openziti/zrok/releases/download/v1.0.7/zrok_1.0.7_windows_amd64.tar.gz -OutFile zrok.tar.gz
    - name: Enable Zrok Headless
      env:
        ZROK_INVITE_TOKEN: ${{ secrets.ZROK_INVITE_TOKEN }}
      run: |
        tar -xf zrok.tar.gz zrok.exe
        mkdir $HOME\.zrok
        .\zrok.exe enable --headless $Env:ZROK_INVITE_TOKEN
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "Windows@10" -Force)
    - name: tunnelin
      run: |
        $output = & .\zrok.exe share public tcp://localhost:3389 --headless --backend-mode proxy
        echo "Tunnel Info:`n$output"
